export const STORE = {
  name: 'THE KINGS AND QUEENS',
  tagline: 'Drip For Kings and Queens',
  momoName: process.env.NEXT_PUBLIC_MOMO_NAME || 'DOMINIC NII KORLEY BOTCHWAY',
  momoNumber: process.env.NEXT_PUBLIC_MOMO_NUMBER || '0260931202',
  whatsapp: process.env.NEXT_PUBLIC_WHATSAPP || '0260931202',
  email: process.env.NEXT_PUBLIC_STORE_EMAIL || 'thekingsandqueens3@gmail.com',
  phone: process.env.NEXT_PUBLIC_STORE_PHONE || '0260931202',
  freeDeliveryThreshold: 500,
  deliveryAccra: 40,
  deliveryOutside: 70,
  adminEmail: process.env.NEXT_PUBLIC_ADMIN_EMAIL || 'admin@thekingsandqueens.com',
  adminPassword: process.env.NEXT_PUBLIC_ADMIN_PASSWORD || 'Admin@2024',
};

export const REGIONS = [
  'Greater Accra',
  'Ashanti',
  'Western',
  'Eastern',
  'Central',
  'Volta',
  'Northern',
  'Upper East',
  'Upper West',
  'Bono',
  'Bono East',
  'Ahafo',
  'Western North',
  'Oti',
  'Savannah',
  'North East',
] as const;
